platform :ios, '10.0'

use_frameworks!

target 'YSAssistProject' do
  
  pod 'SwiftyJSON', '5.0.0'
  
  # 网络传输
  pod 'Alamofire', '5.4.1'
  pod 'Socket.IO-Client-Swift', '15.2.0'
  
  # Rx
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'RxAlamofire', '6.1.1'
  
  # YSKit
  pod 'YSKit', :path => 'LocalPods/YSKit'
  
end
